# Generated by Django 5.2.4 on 2025-09-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
