# Generated by Django 5.2.6 on 2025-09-04 19:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0006_suspiciousip'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
